# Generated by Django 6.0 on 2025-12-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="image_path",
            field=models.CharField(
                blank=True, default="images/default.jpg", max_length=200
            ),
        ),
    ]
