# Generated by Django 6.0 on 2025-12-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_trip_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="description_short",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
