# Generated by Django 6.0 on 2025-12-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_trip_description_short_alter_trip_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("postponed", "Postponed"),
                    ("full", "Full"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
