# Generated by Django 6.0 on 2026-02-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_tripschedule_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="num_participants",
        ),
        migrations.AddField(
            model_name="booking",
            name="adults",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="booking",
            name="children",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
