# Generated by Django 6.0 on 2026-02-07 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_remove_booking_num_participants_booking_adults_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_lastname", models.CharField(max_length=100)),
                ("customer_email", models.EmailField(max_length=254)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 ★"),
                            (2, "2 ★★"),
                            (3, "3 ★★★"),
                            (4, "4 ★★★★"),
                            (5, "5 ★★★★★"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("feedback_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.trip"
                    ),
                ),
            ],
        ),
    ]
